steps:
#Running test cases
- name: maven:3-jdk-11
  entrypoint: mvn
  args: ["test"]
#Running **mvn clean install** and skipping test cases
- name: maven:3-jdk-11
  entrypoint: mvn
  args: ["clean", "install", "-Dmaven.test.skip=true"]
#Deploy image
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  timeout: '1600s'
