# below are the spteps executed by trigger
steps:
# backend deployment
# Step 4: Running maven tests
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]

# Step 5: Running **mvn clean install** and skipping test cases
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["clean", "install", "-Dmaven.test.skip=true"]

# Step 6: Creating docker image using docker file present in server folder
  - name: docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/codecomp-java", "."]

# Step 7: pushing docker image to GCP Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/codecomp-java"]

# Step 8: Deploying this image using app.yaml present in **server/src/main/appengine** to GCP **APP ENGINE**
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'src/main/appengine'
    args: ['app', 'deploy', "--image-url=gcr.io/$PROJECT_ID/codecomp-java"]
    timeout: "30m0s"
images: ["gcr.io/$PROJECT_ID/codecomp-java"]
