# below are the steps executed by trigger
steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["clean", "install", "-Dmaven.test.skip=true"]
        
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["app", "deploy","src/main/appengine/app.yaml"]
    timeout: "1600s"
